Update IkigaiMangas.lua
dazedcat19/FMD pull request #1456
Opened 2024-04-21 07:51 UTC by rs3mk

Update download images

2024-04-21 14:34 UTC, Slasar41 requested changes
Not working.

2024-04-21 17:10 UTC, rs3mk commented
add cookies: data-saving=0

enter: https://ikigaimangas.com/capitulo/962218029541261313/ (accept and generate cookies)

2024-04-22 02:46 UTC, Slasar41 commented
Looks like there's no difference between 0 and 1.

2024-04-22 02:48 UTC, Slasar41 approved these changes

2024-04-22 02:49 UTC, merged