Managanato double entry (fix for #1898)
dazedcat19/FMD pull request #1899
Opened 2024-12-15 17:32 UTC by Stabilostick

2024-12-15 21:37 UTC, Stabilostick commented
Too many work to reorganize the lua scripts into the new format now.

2024-12-16 00:42 UTC, Slasar41 commented
`https://chapmanganato.to` is still needed.
If you check `https://mangakakalot.com` or `https://manganato.com` homepage, some titles has `https://chapmanganato.to` URL.
Users that copied `https://chapmanganato.to` URL will not be recognized by FMD.

2024-12-16 20:04 UTC, Stabilostick commented
Why not add a new source "chapmanganato" with new ID to separate both websites? Seems to be the cleanest solution. And rework this into the new template etc. format. (PS: I know, Manganato itself links most content to chapmanganato, but i have managanato added as main website.)

2024-12-17 01:11 UTC, Slasar41 commented
Just tested `https://chapmanganato.to` to use new ID with old data and it seems fine.

2025-01-14 13:40 UTC, Slasar41 requested changes
Change the ID instead

2025-02-24 08:34 UTC, closed without merging